version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/apps/food-maps-backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/apps/bookshelf-backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/apps/index-watch"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/apps/table-talks"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/apps/otobr-buddy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/apps/ledger-lens-backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/apps/bookshelf-bot"
    schedule:
      interval: "weekly"
