# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: README.md|.*\.iml$
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
        exclude: (devcontainer|package-lock).json
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        args: ["--fix=no"]
