-- No column drop: same rationale as 000003's/000004's down migrations — SQLite can
-- drop a column cheaply as of 3.35+, but no other migration in this repo drops one,
-- so there's no established pattern to follow and the columns are left in place here too.
