import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseChangelogMarkdown } from "../src/lib/changelog";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const appRoot = join(scriptDir, "..");
const changelogPath = join(appRoot, "CHANGELOG.md");
const outputPath = join(appRoot, "src/lib/changelog.generated.ts");

const content = readFileSync(changelogPath, "utf8");
const entries = parseChangelogMarkdown(content);

if (entries.length === 0) {
  console.error(`No version sections found in ${changelogPath}`);
  process.exit(1);
}

const serialized = JSON.stringify(entries, null, 2);
const output = `// Auto-generated by scripts/generate-changelog.ts — do not edit.
import type { ChangelogEntry } from "./changelog";

export const CHANGELOG_ENTRIES: ChangelogEntry[] = ${serialized};
`;

writeFileSync(outputPath, output);
console.log(`Wrote ${entries.length} changelog entries to ${outputPath}`);
