name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  packages: write

jobs:
  main:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set SHAs
        id: set-shas
        uses: nrwl/nx-set-shas@v4

      - name: Run pre-commit and nx targets
        uses: devcontainers/ci@v0.3
        env:
          IMAGE: ghcr.io/tanjd/core-repository
          NX_BASE: ${{ steps.set-shas.outputs.head }}
          NX_HEAD: ${{ steps.set-shas.outputs.base }}
        with:
          imageName: ${{ env.IMAGE }}
          cacheFrom: ${{ env.IMAGE }}
          push: always
          runCmd: |
            pnpm install --frozen-lockfile
            npx nx format:write --verbose
            pre-commit run --all-files
            npx nx affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} -t lint test --verbose
